var files_dup =
[
    [ "env_pwd.c", "env__pwd_8c.html", "env__pwd_8c" ],
    [ "env_setup.c", "env__setup_8c.html", "env__setup_8c" ],
    [ "env_shlvl.c", "env__shlvl_8c.html", "env__shlvl_8c" ],
    [ "exit_failure.c", "exit__failure_8c.html", "exit__failure_8c" ],
    [ "expand.h", "expand_8h_source.html", null ],
    [ "expand_tilde.c", "expand__tilde_8c.html", "expand__tilde_8c" ],
    [ "expand_var.c", "expand__var_8c.html", "expand__var_8c" ],
    [ "ft_string.h", "ft__string_8h_source.html", null ],
    [ "hashtable.h", "hashtable_8h.html", "hashtable_8h" ],
    [ "hashtable_generate.c", "hashtable__generate_8c.html", "hashtable__generate_8c" ],
    [ "hashtable_utils.c", "hashtable__utils_8c.html", "hashtable__utils_8c" ],
    [ "lexer_check_syntax.h", "lexer__check__syntax_8h_source.html", null ],
    [ "lexer_expand.h", "lexer__expand_8h_source.html", null ],
    [ "lexer_list.c", "lexer__list_8c.html", "lexer__list_8c" ],
    [ "lexer_list.h", "lexer__list_8h_source.html", null ],
    [ "lexer_src.c", "lexer__src_8c.html", "lexer__src_8c" ],
    [ "lexer_src.h", "lexer__src_8h_source.html", null ],
    [ "lexer_tok.c", "lexer__tok_8c.html", "lexer__tok_8c" ],
    [ "lexer_tok.h", "lexer__tok_8h_source.html", null ],
    [ "lexer_tok_utils.c", "lexer__tok__utils_8c.html", "lexer__tok__utils_8c" ],
    [ "lexer_tok_utils.h", "lexer__tok__utils_8h_source.html", null ],
    [ "lexer_utils.c", "lexer__utils_8c.html", "lexer__utils_8c" ],
    [ "lexer_utils.h", "lexer__utils_8h_source.html", null ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "minishell.h", "minishell_8h.html", "minishell_8h" ],
    [ "minishell_config.h", "minishell__config_8h_source.html", null ],
    [ "minishell_error.h", "minishell__error_8h.html", "minishell__error_8h" ],
    [ "minishell_struct.h", "minishell__struct_8h_source.html", null ],
    [ "mod_env.h", "mod__env_8h_source.html", null ],
    [ "mod_lexer.h", "mod__lexer_8h_source.html", null ],
    [ "test.h", "test_8h_source.html", null ],
    [ "utils.h", "utils_8h_source.html", null ]
];